// app/embed/[slug]/page.tsx
//
// Minimal embed view — a 600x400 widget showing the portfolio's headline metric,
// a sparkline of the return series, and the top 3 holdings. No DeskShell, no
// navigation, no chrome. Intended for use inside iframes generated by
// ShareButton's embed modal.
"use client";
import { use, useEffect, useState } from "react";
import {
  BG,
  BG_2,
  LINE_2,
  NEGATIVE,
  POSITIVE,
  TEXT_HI,
  TEXT_LOW,
  TEXT_MID,
  VIOLET,
  VIOLET_2,
} from "@/lib/theme";
import type { ProfileData } from "@/lib/queries";
import { initialsFor } from "@/lib/format";

export default function EmbedPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = use(params);
  const [d, setD] = useState<ProfileData | null>(null);
  const [error, setError] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(`/api/profile/${slug}`)
      .then((r) => {
        if (!r.ok) {
          setError(true);
          return null;
        }
        return r.json();
      })
      .then((data) => setD(data))
      .catch(() => setError(true))
      .finally(() => setLoading(false));
  }, [slug]);

  return (
    <div
      className="w-full h-full"
      style={{
        background: BG,
        color: TEXT_HI,
        fontFamily: "var(--font-sans)",
        minHeight: 400,
      }}
    >
      {loading ? (
        <Loading />
      ) : error || !d ? (
        <ErrorState />
      ) : (
        <EmbedCard d={d} slug={slug} />
      )}
    </div>
  );
}

function EmbedCard({ d, slug }: { d: ProfileData; slug: string }) {
  const isLlm = d.kind === "llm";
  const ytdPositive = (d.ytdReturn ?? 0) >= 0;
  const top3 = d.holdings.slice(0, 3);
  return (
    <div
      className="flex flex-col"
      style={{ minHeight: 400, padding: 20 }}
    >
      {/* Brand strip + portrait */}
      <div className="flex items-center gap-3">
        <a
          href={`/`}
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center gap-2 text-[11.5px] font-medium tracking-tight"
          style={{ color: TEXT_HI, textDecoration: "none" }}
        >
          <span
            className="inline-flex items-center justify-center w-5 h-5 rounded"
            style={{
              background: "rgba(255,255,255,0.06)",
              border: `1px solid ${LINE_2}`,
            }}
          >
            <svg width="11" height="11" viewBox="0 0 24 24" fill="none" aria-hidden>
              <path
                d="M4 18 L12 4 L20 18 M7.5 13.5 L16.5 13.5"
                stroke="#fff"
                strokeWidth="2.4"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </span>
          autotrade
        </a>
        <span
          className="ml-auto font-mono text-[9.5px] uppercase tracking-[0.18em]"
          style={{ color: TEXT_LOW }}
        >
          {isLlm ? "AI mind" : "Lawmaker"}
        </span>
      </div>

      {/* Identity */}
      <div className="mt-3 flex items-center gap-3">
        <span
          className="inline-flex items-center justify-center rounded-xl font-semibold text-[16px]"
          style={{
            width: 44,
            height: 44,
            background: isLlm
              ? "linear-gradient(135deg, rgba(124,95,255,0.30), rgba(79,57,216,0.10))"
              : "linear-gradient(135deg, rgba(247,210,74,0.18), rgba(229,189,47,0.05))",
            border: `1px solid ${LINE_2}`,
            color: TEXT_HI,
          }}
        >
          {initialsFor(d.name)}
        </span>
        <div className="flex-1 min-w-0">
          <div className="text-[16px] font-semibold tracking-tight leading-tight truncate" style={{ color: TEXT_HI }}>
            {d.name}
          </div>
          <div className="text-[11px] mt-0.5" style={{ color: TEXT_MID }}>
            {[d.meta.role, d.meta.party, d.meta.house].filter(Boolean).join(" · ")}
          </div>
        </div>
        <div className="text-right">
          <div
            className="text-[20px] font-semibold tabular-nums tracking-tight"
            style={{ color: ytdPositive ? POSITIVE : NEGATIVE }}
          >
            {d.ytdReturn != null
              ? `${ytdPositive ? "+" : ""}${d.ytdReturn.toFixed(1)}%`
              : "—"}
          </div>
          <div
            className="font-mono text-[9.5px] uppercase tracking-[0.18em]"
            style={{ color: TEXT_LOW }}
          >
            YTD
          </div>
        </div>
      </div>

      {/* Sparkline */}
      <Sparkline points={d.portfolioSeries.map((p) => p.value)} positive={ytdPositive} />

      {/* Top holdings */}
      <div className="mt-3 flex-1 flex flex-col">
        <div
          className="font-mono text-[9.5px] uppercase tracking-[0.18em] mb-2"
          style={{ color: TEXT_LOW }}
        >
          Top holdings
        </div>
        <div className="flex flex-col gap-1.5">
          {top3.length === 0 ? (
            <div className="text-[11.5px]" style={{ color: TEXT_LOW }}>
              No positions on file.
            </div>
          ) : (
            top3.map((h) => (
              <div
                key={h.ticker}
                className="flex items-center gap-3 px-2.5 py-1.5 rounded-md"
                style={{
                  background: "rgba(255,255,255,0.02)",
                  border: `1px solid ${LINE_2}`,
                }}
              >
                <span
                  className="font-mono text-[11.5px] font-semibold"
                  style={{ color: TEXT_HI, minWidth: 44 }}
                >
                  {h.ticker}
                </span>
                <span className="text-[10.5px]" style={{ color: TEXT_LOW }}>
                  {h.sector}
                </span>
                <span
                  className="ml-auto font-mono tabular-nums text-[11.5px]"
                  style={{ color: TEXT_MID }}
                >
                  {h.weight.toFixed(1)}%
                </span>
              </div>
            ))
          )}
        </div>
      </div>

      {/* CTA strip */}
      <a
        href={`/${slug}`}
        target="_blank"
        rel="noopener noreferrer"
        className="mt-3 inline-flex items-center justify-center gap-1.5 rounded-full py-1.5 text-[11.5px] font-medium"
        style={{
          background: `linear-gradient(135deg, ${VIOLET} 0%, ${VIOLET_2} 100%)`,
          color: "#fff",
          textDecoration: "none",
          boxShadow: "0 10px 24px -8px rgba(124,95,255,0.55)",
        }}
      >
        Open on autotrade →
      </a>
    </div>
  );
}

function Sparkline({
  points,
  positive,
}: {
  points: number[];
  positive: boolean;
}) {
  if (points.length < 2) {
    return (
      <div
        className="mt-4 rounded-xl flex items-center justify-center text-[11px]"
        style={{
          height: 100,
          background: "rgba(255,255,255,0.02)",
          border: `1px solid ${LINE_2}`,
          color: TEXT_LOW,
        }}
      >
        No history
      </div>
    );
  }
  const w = 560;
  const h = 100;
  const pad = 8;
  const min = Math.min(...points);
  const max = Math.max(...points);
  const range = max - min || 1;
  const stepX = (w - pad * 2) / (points.length - 1);
  const toY = (v: number) => h - pad - ((v - min) / range) * (h - pad * 2);
  let path = "";
  points.forEach((p, i) => {
    const x = pad + i * stepX;
    const y = toY(p);
    path += i === 0 ? `M ${x} ${y}` : ` L ${x} ${y}`;
  });
  const fillPath = `${path} L ${pad + (points.length - 1) * stepX} ${h - pad} L ${pad} ${h - pad} Z`;
  const color = positive ? POSITIVE : NEGATIVE;
  return (
    <div
      className="mt-4 rounded-xl overflow-hidden"
      style={{
        background: "rgba(255,255,255,0.02)",
        border: `1px solid ${LINE_2}`,
      }}
    >
      <svg viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none" style={{ width: "100%", height: 100, display: "block" }}>
        <defs>
          <linearGradient id="spark-fill" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" stopColor={color} stopOpacity="0.28" />
            <stop offset="100%" stopColor={color} stopOpacity="0" />
          </linearGradient>
        </defs>
        <path d={fillPath} fill="url(#spark-fill)" />
        <path d={path} stroke={color} strokeWidth="1.6" fill="none" strokeLinecap="round" strokeLinejoin="round" />
      </svg>
    </div>
  );
}

function Loading() {
  return (
    <div
      className="flex items-center justify-center"
      style={{ minHeight: 400, color: TEXT_LOW }}
    >
      <span className="font-mono text-[11px] uppercase tracking-[0.18em]">Loading…</span>
    </div>
  );
}

function ErrorState() {
  return (
    <div
      className="flex flex-col items-center justify-center text-center px-6"
      style={{ minHeight: 400 }}
    >
      <div
        className="font-mono text-[10px] uppercase tracking-[0.18em]"
        style={{ color: TEXT_LOW }}
      >
        autotrade
      </div>
      <div className="mt-2 text-[14px] font-medium" style={{ color: TEXT_HI }}>
        Portfolio not found
      </div>
      <a
        href="/"
        target="_blank"
        rel="noopener noreferrer"
        className="mt-3 text-[12px]"
        style={{ color: VIOLET_2 }}
      >
        Open autotrade →
      </a>
    </div>
  );
}
